// Order -> MercadoPago pay link, shared by the agent (WhatsApp) and web Brick.
// Hold-first: creates a payments row + Checkout Pro preference, flips the order to
// 'awaiting_payment' with a hold expiry, and returns the init_point URL. Rolls
// back the payments row on MP failure so we never leave a dangling hold.
import type { Db } from "./supabase.ts";
import { createPreference, createSubscription } from "./mercadopago.ts";

export const HOLD_MINUTES = 30; // matches Webpay's 30-min auto-cancel

function webhookUrl(): string {
  const base = Deno.env.get("SUPABASE_URL");
  if (!base) throw new Error("Missing SUPABASE_URL");
  return `${base}/functions/v1/mercadopago-webhook`;
}

function siteUrl(): string {
  return Deno.env.get("PUBLIC_SITE_URL") ?? "https://huevos-donald.vercel.app";
}

export interface OrderPayLink {
  paymentUrl: string;
  preferenceId: string;
  externalReference: string;
  amountCents: number;
  holdMinutes: number;
  expiresAt: string;
}

/**
 * Create (or reuse) a Checkout Pro pay link for an existing order.
 * `source` tags which channel will deliver the "paid" confirmation later.
 */
export async function createOrderPaymentLink(
  db: Db,
  opts: { orderId: string; source: "web" | "whatsapp" | "agent"; payerEmail?: string },
): Promise<OrderPayLink> {
  const { data: order, error: orderErr } = await db
    .from("orders")
    .select("id, amount_cents, currency, quantity, user_id, status")
    .eq("id", opts.orderId)
    .single();
  if (orderErr || !order) throw new Error(`createOrderPaymentLink: order not found (${orderErr?.message})`);

  const expiresAt = new Date(Date.now() + HOLD_MINUTES * 60_000).toISOString();

  // 1) Insert the payments hold row; external_reference is generated by the DB.
  const { data: pay, error: payErr } = await db
    .from("payments")
    .insert({
      order_id: order.id,
      user_id: order.user_id,
      amount_cents: order.amount_cents,
      currency: order.currency,
      status: "pending",
      source: opts.source,
      expires_at: expiresAt,
    })
    .select("id, external_reference")
    .single();
  if (payErr || !pay) throw new Error(`createOrderPaymentLink: payments insert failed (${payErr?.message})`);

  try {
    // 2) Create the MP preference.
    const pref = await createPreference({
      amountCents: order.amount_cents,
      title: `Pedido Huevos Donald (${order.quantity} huevos)`,
      quantity: 1, // unit_price already carries the full order amount
      externalReference: pay.external_reference,
      notificationUrl: webhookUrl(),
      successUrl: `${siteUrl()}/pago/exito`,
      pendingUrl: `${siteUrl()}/pago/pendiente`,
      failureUrl: `${siteUrl()}/pago/error`,
      payerEmail: opts.payerEmail,
      metadata: { order_id: order.id, source: opts.source },
      expiresAt,
    });
    const initPoint = pref.init_point || pref.sandbox_init_point;

    // 3) Persist MP ids on the payment.
    await db
      .from("payments")
      .update({ mp_preference_id: pref.id, mp_init_point: initPoint })
      .eq("id", pay.id);

    // 4) Move the order into the hold state.
    await db
      .from("orders")
      .update({ status: "awaiting_payment", payment_expires_at: expiresAt })
      .eq("id", order.id);

    return {
      paymentUrl: initPoint,
      preferenceId: pref.id,
      externalReference: pay.external_reference,
      amountCents: order.amount_cents,
      holdMinutes: HOLD_MINUTES,
      expiresAt,
    };
  } catch (err) {
    // Roll back the hold row so the order can be retried cleanly.
    await db.from("payments").delete().eq("id", pay.id);
    throw err;
  }
}

// ── Recurring subscriptions (MP preapproval, redirect flow) ───────────────────
const FREQ_MAP: Record<string, { frequency: number; frequencyType: "days" | "months" }> = {
  weekly: { frequency: 7, frequencyType: "days" },
  biweekly: { frequency: 14, frequencyType: "days" },
  monthly: { frequency: 1, frequencyType: "months" },
};

export interface SubscriptionCheckout {
  subscribeUrl: string;
  preapprovalId: string;
  externalReference: string;
  amountCents: number;
}

/**
 * Create a subscription (preapproval) for a plan and return the MP redirect URL
 * where the customer enters their card. We persist a 'pending' subscription row;
 * the webhook flips it to 'authorized' once MP confirms. Rolls back on failure.
 */
export async function createSubscriptionCheckout(
  db: Db,
  opts: {
    planId: string;
    payerEmail: string;
    userId: string; // subscriptions are login-only — always tied to an auth user
    source: "web" | "whatsapp" | "agent";
    contactPhone?: string;
    deliveryZoneId?: string;
    preferredSlotId?: string;
    preferredWeekday?: number;
  },
): Promise<SubscriptionCheckout> {
  const { data: plan, error: planErr } = await db
    .from("plans")
    .select("id, name, price_cents, frequency, quantity_per_delivery")
    .eq("id", opts.planId)
    .eq("active", true)
    .maybeSingle();
  if (planErr || !plan) throw new Error(`createSubscriptionCheckout: plan not found (${planErr?.message})`);

  const freq = FREQ_MAP[plan.frequency] ?? FREQ_MAP.monthly;

  const { data: sub, error: subErr } = await db
    .from("subscriptions")
    .insert({
      plan_id: plan.id,
      user_id: opts.userId,
      status: "pending",
      contact_email: opts.payerEmail,
      contact_phone: opts.contactPhone ?? null,
      source: opts.source,
      delivery_zone_id: opts.deliveryZoneId ?? null,
      preferred_slot_id: opts.preferredSlotId ?? null,
      preferred_weekday: opts.preferredWeekday ?? null,
    })
    .select("id, external_reference")
    .single();
  if (subErr || !sub) throw new Error(`createSubscriptionCheckout: subscription insert failed (${subErr?.message})`);

  try {
    const pre = await createSubscription({
      reason: `${plan.name} — Huevos Donald (${plan.quantity_per_delivery} huevos por entrega)`,
      amountCents: plan.price_cents,
      payerEmail: opts.payerEmail,
      externalReference: sub.external_reference,
      backUrl: `${siteUrl()}/suscripcion/listo`,
      frequency: freq.frequency,
      frequencyType: freq.frequencyType,
    });
    const url = pre.init_point || pre.sandbox_init_point || "";

    await db
      .from("subscriptions")
      .update({
        mercadopago_subscription_id: pre.id,
        next_billing_at: (pre.next_payment_date as string | undefined) ?? null,
      })
      .eq("id", sub.id);

    return {
      subscribeUrl: url,
      preapprovalId: pre.id,
      externalReference: sub.external_reference,
      amountCents: plan.price_cents,
    };
  } catch (err) {
    await db.from("subscriptions").delete().eq("id", sub.id);
    throw err;
  }
}
